server:
  port: 38091
eureka:
  dashboard:
    path: /server-center
    enabled: true
  instance:
    hostname: server-center2
    prefer-ip-address: true
    instance-id: server-center39091
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:38090/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
    wait-time-in-ms-when-sync-empty: 0