
server:
  port: 38093
  servlet:
    context-path: /auth
# 验证码配置
kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYAZ
    space: 2
  font:
    color: blue
    name: 宋体,楷体,微软雅黑
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1
eureka:
  client:
    service-url:

      defaultZone: http://172.17.233.201:38090/eureka/,http://172.17.233.201:38091/eureka/
    # 从eureka 上获取服务列表时间 30
    registry-fetch-interval-seconds: 30
    # 复制实例变化信息到eureka服务器所需要的时间间隔
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: authApplication
    #   Eureka服务器在接收到本实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除
    lease-renewal-interval-in-seconds: 30
    #  eureka客户需要多长时间发送心跳给eureka服务器
    lease-expiration-duration-in-seconds: 15

spring:
  application:
    name: authApplication
