server:
  port: 38092
  servlet:
    context-path: /config
spring:
  application:
    name: configApplication
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangxiao1002/config
          username: *****
          password: ****
          # 文件夹
          search-paths: config
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://123.57.243.207:38090/eureka/;http://123.57.243.207:38091/eureka/
    # 从eureka 上获取服务列表时间 30
    registry-fetch-interval-seconds: 30
    # 复制实例变化信息到eureka服务器所需要的时间间隔
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: configApplication
    #   Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除
    lease-renewal-interval-in-seconds: 10
    #  eureka客户需要多长时间发送心跳给eureka服务器
    lease-expiration-duration-in-seconds: 5


