server:
  port: 38092
  servlet:
    context-path: /config
spring:
  application:
    name: configApplication
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangxiao1002/config
          username: wangxiao1002
          password: HEchuTIANya1.
          # 文件夹
          search-paths: config
          default-label: master
  security:
    user:
      name: sy
      password: sy123.
eureka:
  client:
    service-url:
      defaultZone: http://172.17.233.201:38090/eureka/,http://172.17.233.201:38091/eureka/
    # 从eureka 上获取服务列表时间 30
    registry-fetch-interval-seconds: 30
    # 复制实例变化信息到eureka服务器所需要的时间间隔
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: configApplication${server.port}
    #   Eureka服务器在接收到本实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除
    lease-renewal-interval-in-seconds: 30
    #  eureka客户需要多长时间发送心跳给eureka服务器
    lease-expiration-duration-in-seconds: 15
    # 添加地址后 客户端获取地址不加 /config
    metadata-map:
      configPath: ${server.servlet.context-path}
      management:
        context-path: ${server.servlet.context-path}/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
